apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-cert
  namespace: idemiafoot
spec:
  secretName: frontend-tls
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer
  commonName: dev.foot-idemia.fr
  dnsNames:
  - dev.foot-idemia.fr
