apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: idemiafoot
spec:
  secretName: minio-tls
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer
  commonName: s3.dev.foot-idemia.fr
  dnsNames:
  - s3.dev.foot-idemia.fr

