apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-cert
  namespace: idemiafoot
spec:
  secretName: backend-tls
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer
  commonName: api.dev.foot-idemia.fr
  dnsNames:
  - api.dev.foot-idemia.fr

