apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    # Configure your email here...
    # ---
    email: loic.verniere@icloud.com

    # Configure your server here...
    # ---
    # Letsencrypt Production
    server: https://acme-v02.api.letsencrypt.org/directory
    # - or -
    # Letsencrypt Staging
    #server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    # Configure DNS or HTTP Challenge here...
    # ---
    # DNS Challenge:
    - dns01:
        # Configure your DNS Provider here...
        # ---
        cloudflare:
          email: idemia.foot@gmail.com
    #     # API Key:
    #       apiKeySecretRef:
    #         name: cloudflare-api-key-secret
    #         key: api-key
        # - or -
        #API Token:
          apiTokenSecretRef:
            name: cloudflare-api-key-secret
            key: api-token        
      # (Optional) Add DNS selectors
      # ---
    # HTTP Challenge:
    - http01:
       ingress:
         class: traefik
         ingressTemplate:
            metadata:
              annotations:
                "traefik.ingress.kubernetes.io/frontend-entry-points": "http"
