apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt-dev
spec:
  acme:
    email: loic.verniere@icloud.com
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-dev
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: traefik
            ingressTemplate:
              metadata:
                annotations:
                  traefik.ingress.kubernetes.io/backend-entry-points: http
