# dns internal : redis-service.idemiafoot.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: idemiafoot
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:latest
          name: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: idemiafoot
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

